#!/usr/bin/env python3
"""
Hero 云台动力学参数辨识工具

辨识 9 个参数 (theta0-theta8)：
  theta0/theta1 = 耦合惯量 (I1zz_com, I2xx_com)
  theta2        = Pitch 惯量 (I2yy_com)
  theta3/theta4 = 重力项 (m2*l2x, m2*l2z)
  theta5/theta6 = Yaw 摩擦 (fv1, fc1)
  theta7/theta8 = Pitch 摩擦 (fv2, fc2)

用法:
  python identify_gimbal.py gravity  gravity_static.csv
  python identify_gimbal.py friction friction_sweep.csv
  python identify_gimbal.py pitch    dynamic_pitch.csv
  python identify_gimbal.py coupling dynamic_yaw_q2_*.csv
  python identify_gimbal.py verify   dynamic_harmonics.csv
  python identify_gimbal.py guide
"""

import argparse
import sys
import os
import numpy as np
import pandas as pd
from pathlib import Path

# 依赖检查
try:
    from scipy.signal import savgol_filter
except ImportError:
    print("[ERROR] 需要安装 scipy: pip install scipy")
    sys.exit(1)

G = 9.81  # m/s^2


# ─────────────────────────── 数据加载 ───────────────────────────

def load_csv(path: str) -> pd.DataFrame:
    """加载辨识 CSV，列: time, q1, q2, dq1, dq2, tau1, tau2"""
    df = pd.read_csv(path)
    required = {"time", "q1", "q2", "dq1", "dq2", "tau1", "tau2"}
    if not required.issubset(set(df.columns)):
        missing = required - set(df.columns)
        print(f"[ERROR] CSV 缺少列: {missing}")
        print(f"  当前列: {list(df.columns)}")
        sys.exit(1)
    # 转为 float
    for c in df.columns:
        df[c] = df[c].astype(float)
    print(f"  已加载 {len(df)} 行, 时间范围 [{df['time'].iloc[0]:.3f}, {df['time'].iloc[-1]:.3f}] s")
    return df


def save_theta(theta: np.ndarray, output: str = None):
    """打印 theta 并可选保存到文件"""
    print("\n" + "=" * 50)
    print("辨识结果 (kIdentTheta[9]):")
    print("=" * 50)
    labels = [
        "theta0: I1zz_com  (yaw 耦合惯量)",
        "theta1: I2xx_com  (yaw 耦合惯量)",
        "theta2: I2yy_com  (pitch 惯量)",
        "theta3: m2*l2x    (重力水平偏心)",
        "theta4: m2*l2z    (重力垂直偏心)",
        "theta5: fv1       (yaw 粘滞摩擦)",
        "theta6: fc1       (yaw 库仑摩擦)",
        "theta7: fv2       (pitch 粘滞摩擦)",
        "theta8: fc2       (pitch 库仑摩擦)",
    ]
    for i, (v, lbl) in enumerate(zip(theta, labels)):
        print(f"  [{i}] {v:12.6f}  {lbl}")

    # C++ 数组格式
    cpp_lines = []
    for i, (v, lbl) in enumerate(zip(theta, labels)):
        comma = "," if i < 8 else ""
        cpp_lines.append(f"    {v:.6f}f{comma}  // {lbl}")
    cpp_block = "constexpr float kIdentTheta[9] = {\n" + "\n".join(cpp_lines) + "\n};"
    print("\n── 可复制到 params.hpp ──")
    print(cpp_block)

    if output:
        with open(output, "w") as f:
            f.write("// Auto-generated by identify_gimbal.py\n")
            f.write(cpp_block + "\n")
        print(f"\n已保存到 {output}")


# ─────────────────────────── Step 1: 重力辨识 ───────────────────────────

def identify_gravity(df: pd.DataFrame):
    """
    辨识 theta3 (m2*l2x) 和 theta4 (m2*l2z)

    模型: tau2 = -g * (theta3*cos(q2) + theta4*sin(q2)) + C
    即:   tau2 = A*cos(q2) + B*sin(q2) + C
    所以:  theta3 = -A/g, theta4 = -B/g
    """
    print("\n" + "=" * 50)
    print("Step 1: 重力项辨识 (theta3, theta4)")
    print("=" * 50)

    # 筛选静态数据: 速度接近零
    vel_thresh = 0.02  # rad/s
    mask = (df["dq1"].abs() < vel_thresh) & (df["dq2"].abs() < vel_thresh)
    df_static = df[mask].copy()
    print(f"  静态数据点: {len(df_static)} / {len(df)}")

    if len(df_static) < 10:
        print("  [WARN] 静态数据太少，使用全部数据（假设近似静态）")
        df_static = df

    # 按角度分箱取平均，减少噪声
    q2_bins = np.linspace(df_static["q2"].min(), df_static["q2"].max(), 20)
    df_static = df_static.copy()
    df_static["q2_bin"] = np.digitize(df_static["q2"], q2_bins)
    grouped = df_static.groupby("q2_bin").agg({"q2": "mean", "tau2": "mean", "dq2": "mean"}).dropna()

    q2 = grouped["q2"].values
    tau2 = grouped["tau2"].values

    # 线性最小二乘: tau2 = A*cos(q2) + B*sin(q2) + C
    Y = np.column_stack([np.cos(q2), np.sin(q2), np.ones_like(q2)])
    result, residuals, rank, sv = np.linalg.lstsq(Y, tau2, rcond=None)
    A, B, C = result

    theta3 = -A / G
    theta4 = -B / G

    # R²
    tau2_pred = Y @ result
    ss_res = np.sum((tau2 - tau2_pred) ** 2)
    ss_tot = np.sum((tau2 - np.mean(tau2)) ** 2)
    r2 = 1 - ss_res / ss_tot if ss_tot > 0 else 0

    print(f"\n  拟合结果:")
    print(f"    A = {A:.6f}, B = {B:.6f}, C = {C:.6f}")
    print(f"    theta3 (m2*l2x) = {theta3:.6f}")
    print(f"    theta4 (m2*l2z) = {theta4:.6f}")
    print(f"    常值偏置 C = {C:.6f}  {'(正常)' if abs(C) < 1.0 else '(偏大，检查零偏)'}")
    print(f"    R² = {r2:.6f}")

    theta = np.zeros(9)
    theta[3] = theta3
    theta[4] = theta4
    save_theta(theta)
    return theta


# ─────────────────────────── Step 2: 摩擦辨识 ───────────────────────────

def identify_friction(df: pd.DataFrame, theta3: float, theta4: float):
    """
    辨识 theta5/theta6 (yaw 摩擦) 和 theta7/theta8 (pitch 摩擦)

    Yaw:  tau1 = theta5*dq1 + theta6*tanh(dq1)
    Pitch: tau2_no_grav = theta7*dq2 + theta8*tanh(dq2)
    """
    print("\n" + "=" * 50)
    print("Step 2: 摩擦项辨识 (theta5, theta6, theta7, theta8)")
    print("=" * 50)

    theta = np.zeros(9)
    theta[3] = theta3
    theta[4] = theta4

    # ── Yaw 摩擦 ──
    print("\n  [Yaw 摩擦]")
    # 筛选匀速段: 加速度小
    v_eps = 0.02  # 最小速度阈值
    a_thresh = 0.5  # rad/s^2
    # 用差分近似加速度
    dq1_diff = np.gradient(df["dq1"], df["time"])
    mask_yaw = (df["dq1"].abs() > v_eps) & (np.abs(dq1_diff) < a_thresh)
    df_yaw = df[mask_yaw].copy()
    print(f"    匀速数据点: {len(df_yaw)} / {len(df)}")

    if len(df_yaw) < 10:
        print("    [WARN] 匀速数据太少，使用全部数据")
        df_yaw = df

    dq1 = df_yaw["dq1"].values
    tau1 = df_yaw["tau1"].values

    # tau1 = fv1*dq1 + fc1*tanh(dq1)
    Y_yaw = np.column_stack([dq1, np.tanh(dq1)])
    result_yaw, _, _, _ = np.linalg.lstsq(Y_yaw, tau1, rcond=None)
    theta5, theta6 = result_yaw

    tau1_pred = Y_yaw @ result_yaw
    ss_res = np.sum((tau1 - tau1_pred) ** 2)
    ss_tot = np.sum((tau1 - np.mean(tau1)) ** 2)
    r2_yaw = 1 - ss_res / ss_tot if ss_tot > 0 else 0

    print(f"    theta5 (fv1) = {theta5:.6f}")
    print(f"    theta6 (fc1) = {theta6:.6f}")
    print(f"    R² = {r2_yaw:.6f}")

    # ── Pitch 摩擦 ──
    print("\n  [Pitch 摩擦]")
    # 扣除重力
    tau_gravity = -G * (theta3 * np.cos(df["q2"].values) + theta4 * np.sin(df["q2"].values))
    tau2_no_grav = df["tau2"].values - tau_gravity

    # 筛选匀速段
    dq2_diff = np.gradient(df["dq2"], df["time"])
    mask_pitch = (df["dq2"].abs() > v_eps) & (np.abs(dq2_diff) < a_thresh)
    df_pitch = df[mask_pitch].copy()
    tau2_ng_pitch = tau2_no_grav[mask_pitch]
    print(f"    匀速数据点: {len(df_pitch)} / {len(df)}")

    if len(df_pitch) < 10:
        print("    [WARN] 匀速数据太少，使用全部数据")
        df_pitch = df
        tau2_ng_pitch = tau2_no_grav

    dq2 = df_pitch["dq2"].values

    # tau2_no_grav = fv2*dq2 + fc2*tanh(dq2)
    Y_pitch = np.column_stack([dq2, np.tanh(dq2)])
    result_pitch, _, _, _ = np.linalg.lstsq(Y_pitch, tau2_ng_pitch, rcond=None)
    theta7, theta8 = result_pitch

    tau2_pred = Y_pitch @ result_pitch
    ss_res = np.sum((tau2_ng_pitch - tau2_pred) ** 2)
    ss_tot = np.sum((tau2_ng_pitch - np.mean(tau2_ng_pitch)) ** 2)
    r2_pitch = 1 - ss_res / ss_tot if ss_tot > 0 else 0

    print(f"    theta7 (fv2) = {theta7:.6f}")
    print(f"    theta8 (fc2) = {theta8:.6f}")
    print(f"    R² = {r2_pitch:.6f}")

    theta[5] = theta5
    theta[6] = theta6
    theta[7] = theta7
    theta[8] = theta8
    save_theta(theta)
    return theta


# ─────────────────────────── Step 3: Pitch 惯量辨识 ───────────────────────────

def identify_pitch_inertia(df: pd.DataFrame, theta3: float, theta4: float,
                           theta7: float, theta8: float):
    """
    辨识 theta2 (I2yy_com)

    tau2_residual = theta2 * ddq2
    其中 tau2_residual = tau2 - tau2_gravity - tau2_friction
    """
    print("\n" + "=" * 50)
    print("Step 3: Pitch 惯量辨识 (theta2)")
    print("=" * 50)

    # 计算 ddq2 (用 Savitzky-Golay 滤波)
    dt = np.mean(np.diff(df["time"]))
    dq2 = df["dq2"].values
    # Savitzky-Golay 滤波求导
    window = min(51, len(dq2) // 4 * 2 + 1)  # 奇数窗口
    if window < 5:
        window = 5
    ddq2 = savgol_filter(dq2, window, 3, deriv=1, delta=dt)

    # 扣除重力
    q2 = df["q2"].values
    tau2 = df["tau2"].values
    tau_gravity = -G * (theta3 * np.cos(q2) + theta4 * np.sin(q2))

    # 扣除摩擦
    tau_friction = theta7 * dq2 + theta8 * np.tanh(dq2)

    tau2_residual = tau2 - tau_gravity - tau_friction

    # 筛选有效数据: ddq 不能太小
    ddq_thresh = 0.1  # rad/s^2
    mask = np.abs(ddq2) > ddq_thresh
    ddq2_valid = ddq2[mask]
    tau2_res_valid = tau2_residual[mask]
    print(f"  有效数据点: {np.sum(mask)} / {len(df)}")

    if np.sum(mask) < 10:
        print("  [WARN] 有效数据太少，使用全部数据")
        ddq2_valid = ddq2
        tau2_res_valid = tau2_residual

    # 最小二乘: tau2_residual = theta2 * ddq2
    result = np.linalg.lstsq(ddq2_valid.reshape(-1, 1), tau2_res_valid, rcond=None)
    theta2 = result[0][0]

    tau2_pred = ddq2_valid * theta2
    ss_res = np.sum((tau2_res_valid - tau2_pred) ** 2)
    ss_tot = np.sum((tau2_res_valid - np.mean(tau2_res_valid)) ** 2)
    r2 = 1 - ss_res / ss_tot if ss_tot > 0 else 0

    print(f"  theta2 (I2yy_com) = {theta2:.6f}")
    print(f"  R² = {r2:.6f}")
    if theta2 < 0:
        print("  [WARN] 惯量为负，检查数据质量")

    theta = np.zeros(9)
    theta[2] = theta2
    theta[3] = theta3
    theta[4] = theta4
    theta[5] = 0  # 不在此步辨识
    theta[6] = 0
    theta[7] = theta7
    theta[8] = theta8
    save_theta(theta)
    return theta


# ─────────────────────────── Step 4: 耦合惯量辨识 ───────────────────────────

def identify_coupling(files: list, theta5: float, theta6: float):
    """
    辨识 theta0/theta1 (I1zz_com, I2xx_com)

    在多个固定 q2 角度下:
    tau1_residual = (theta0*sin²(q2) + theta1*cos²(q2)) * ddq1
    """
    print("\n" + "=" * 50)
    print("Step 4: Yaw-Pitch 耦合惯量辨识 (theta0, theta1)")
    print("=" * 50)

    all_ddq1 = []
    all_tau1_res = []
    all_sin2 = []
    all_cos2 = []

    for f in files:
        print(f"\n  处理: {f}")
        df = load_csv(f)

        dt = np.mean(np.diff(df["time"]))
        dq1 = df["dq1"].values
        window = min(51, len(dq1) // 4 * 2 + 1)
        if window < 5:
            window = 5
        ddq1 = savgol_filter(dq1, window, 3, deriv=1, delta=dt)

        # 扣除 yaw 摩擦
        tau_friction = theta5 * dq1 + theta6 * np.tanh(dq1)
        tau1_residual = df["tau1"].values - tau_friction

        # q2 取平均值（固定 pitch 角度）
        q2_mean = np.mean(df["q2"].values)
        sin2 = np.sin(q2_mean) ** 2
        cos2 = np.cos(q2_mean) ** 2

        # 筛选有效数据
        ddq_thresh = 0.1
        mask = np.abs(ddq1) > ddq_thresh
        print(f"    q2 = {np.degrees(q2_mean):.1f}°, 有效点: {np.sum(mask)} / {len(df)}")

        all_ddq1.append(ddq1[mask])
        all_tau1_res.append(tau1_residual[mask])
        all_sin2.append(np.full(np.sum(mask), sin2))
        all_cos2.append(np.full(np.sum(mask), cos2))

    ddq1_all = np.concatenate(all_ddq1)
    tau1_res_all = np.concatenate(all_tau1_res)
    sin2_all = np.concatenate(all_sin2)
    cos2_all = np.concatenate(all_cos2)

    # 最小二乘: tau1_residual = theta0*sin²(q2)*ddq1 + theta1*cos²(q2)*ddq1
    Y = np.column_stack([sin2_all * ddq1_all, cos2_all * ddq1_all])
    result, _, _, _ = np.linalg.lstsq(Y, tau1_res_all, rcond=None)
    theta0, theta1 = result

    tau1_pred = Y @ result
    ss_res = np.sum((tau1_res_all - tau1_pred) ** 2)
    ss_tot = np.sum((tau1_res_all - np.mean(tau1_res_all)) ** 2)
    r2 = 1 - ss_res / ss_tot if ss_tot > 0 else 0

    print(f"\n  theta0 (I1zz_com) = {theta0:.6f}")
    print(f"  theta1 (I2xx_com) = {theta1:.6f}")
    print(f"  R² = {r2:.6f}")

    theta = np.zeros(9)
    theta[0] = theta0
    theta[1] = theta1
    theta[5] = theta5
    theta[6] = theta6
    save_theta(theta)
    return theta


# ─────────────────────────── Step 5: 五次谐波验证 ───────────────────────────

def verify_harmonics(df: pd.DataFrame, theta: np.ndarray):
    """
    五次谐波综合验证

    比较模型预测力矩与实际力矩，计算跟踪误差
    """
    print("\n" + "=" * 50)
    print("Step 5: 五次谐波综合验证")
    print("=" * 50)

    q1 = df["q1"].values
    q2 = df["q2"].values
    dq1 = df["dq1"].values
    dq2 = df["dq2"].values
    tau1 = df["tau1"].values
    tau2 = df["tau2"].values

    # 计算 ddq
    dt = np.mean(np.diff(df["time"]))
    window = min(51, len(dq1) // 4 * 2 + 1)
    if window < 5:
        window = 5
    ddq1 = savgol_filter(dq1, window, 3, deriv=1, delta=dt)
    ddq2 = savgol_filter(dq2, window, 3, deriv=1, delta=dt)

    # 构建回归矩阵 Y (2x9)
    sin_q1 = np.sin(q1)
    cos_q1 = np.cos(q1)
    sin_q2 = np.sin(q2)
    cos_q2 = np.cos(q2)
    sin_2q2 = 2 * sin_q2 * cos_q2
    sin2_q2 = sin_q2 ** 2
    cos2_q2 = cos_q2 ** 2
    dq1_dq2 = dq1 * dq2
    dq1_sq = dq1 ** 2

    # 重力: g = [0, 0, -9.81]
    gx, gy, gz = 0.0, 0.0, -9.81
    gx_sin_gy_cos_q1 = gx * sin_q1 - gy * cos_q1
    gx_cos_gy_sin_q1 = gx * cos_q1 + gy * sin_q1

    N = len(q1)
    Y_mat = np.zeros((2 * N, 9))

    # Yaw 轴 (行 0..N-1)
    Y_mat[:N, 0] = sin2_q2 * ddq1 + sin_2q2 * dq1_dq2
    Y_mat[:N, 1] = cos2_q2 * ddq1 - sin_2q2 * dq1_dq2
    Y_mat[:N, 3] = gx_sin_gy_cos_q1 * cos_q2
    Y_mat[:N, 4] = gx_sin_gy_cos_q1 * sin_q2
    Y_mat[:N, 5] = dq1
    Y_mat[:N, 6] = np.tanh(dq1)

    # Pitch 轴 (行 N..2N-1)
    Y_mat[N:, 0] = -0.5 * sin_2q2 * dq1_sq
    Y_mat[N:, 1] = 0.5 * sin_2q2 * dq1_sq
    Y_mat[N:, 2] = ddq2
    Y_mat[N:, 3] = gx_cos_gy_sin_q1 * sin_q2 + gz * cos_q2
    Y_mat[N:, 4] = -gx_cos_gy_sin_q1 * cos_q2 + gz * sin_q2
    Y_mat[N:, 7] = dq2
    Y_mat[N:, 8] = np.tanh(dq2)

    # 预测力矩
    tau_pred = Y_mat @ theta
    tau1_pred = tau_pred[:N]
    tau2_pred = tau_pred[N:]

    # 误差统计
    err1 = tau1 - tau1_pred
    err2 = tau2 - tau2_pred

    rmse1 = np.sqrt(np.mean(err1 ** 2))
    rmse2 = np.sqrt(np.mean(err2 ** 2))
    mae1 = np.mean(np.abs(err1))
    mae2 = np.mean(np.abs(err2))

    print(f"\n  Yaw  跟踪误差: RMSE = {rmse1:.4f} Nm, MAE = {mae1:.4f} Nm")
    print(f"  Pitch 跟踪误差: RMSE = {rmse2:.4f} Nm, MAE = {mae2:.4f} Nm")

    # 各项分解
    print(f"\n  Yaw 力矩分解 (均方根):")
    print(f"    惯量项:  {np.sqrt(np.mean((Y_mat[:N, 0] * theta[0] + Y_mat[:N, 1] * theta[1]) ** 2)):.4f}")
    print(f"    重力项:  {np.sqrt(np.mean((Y_mat[:N, 3] * theta[3] + Y_mat[:N, 4] * theta[4]) ** 2)):.4f}")
    print(f"    摩擦项:  {np.sqrt(np.mean((Y_mat[:N, 5] * theta[5] + Y_mat[:N, 6] * theta[6]) ** 2)):.4f}")

    print(f"\n  Pitch 力矩分解 (均方根):")
    print(f"    耦合项:  {np.sqrt(np.mean((Y_mat[N:, 0] * theta[0] + Y_mat[N:, 1] * theta[1]) ** 2)):.4f}")
    print(f"    惯量项:  {np.sqrt(np.mean((Y_mat[N:, 2] * theta[2]) ** 2)):.4f}")
    print(f"    重力项:  {np.sqrt(np.mean((Y_mat[N:, 3] * theta[3] + Y_mat[N:, 4] * theta[4]) ** 2)):.4f}")
    print(f"    摩擦项:  {np.sqrt(np.mean((Y_mat[N:, 7] * theta[7] + Y_mat[N:, 8] * theta[8]) ** 2)):.4f}")

    return {"rmse_yaw": rmse1, "rmse_pitch": rmse2, "mae_yaw": mae1, "mae_pitch": mae2}


# ─────────────────────────── 操作指导 ───────────────────────────

def print_guide():
    """打印完整的辨识操作指导"""
    guide = """
╔══════════════════════════════════════════════════════════════╗
║           Hero 云台动力学参数辨识操作指南                      ║
╚══════════════════════════════════════════════════════════════╝

【前置准备】
1. 编译 Hero 固件: 修改 params.hpp 第 10 行 WHEEL_LEGGED_ROBOT_VARIANT = 1
2. 烧录到机器人
3. 连接串口 (默认 COM7, 115200 baud)
4. 安装 Python 依赖: pip install numpy pandas scipy matplotlib

【遥控器操作】
  左拨杆 DOWN + 右拨杆 UP   → 辨识模式 (五次谐波轨迹 + PID 位置环)
  左拨杆 DOWN + 右拨杆 MID  → 前馈验证模式 (纯动力学前馈)
  其他组合                   → 正常模式

【辨识流程 (严格按顺序执行)】

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Step 1: 重力项辨识 (theta3, theta4)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  目标: 辨识 m2*l2x (水平偏心) 和 m2*l2z (垂直偏心)

  操作:
  1. 机器人固定底座，Yaw 锁定在 q1=0
  2. 手动将 Pitch 移到不同角度: -30°, -20°, -10°, 0°, 10°, 20°, 30°
  3. 每个角度停留 1-2 秒，确保速度为零
  4. 用串口采集数据:
     python serial_collect.py gravity --port COM7
  5. 按 Ctrl+C 停止

  分析:
     python identify_gimbal.py gravity gravity_static.csv

  验证:
  - R² 应 > 0.95
  - 常值偏置 C 应 < 1.0 Nm
  - theta3/theta4 符号应合理 (取决于坐标系定义)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Step 2: 摩擦项辨识 (theta5, theta6, theta7, theta8)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  目标: 辨识 Yaw/Pitch 的粘滞摩擦和库仑摩擦

  操作:
  1. Yaw 低速匀速扫角: ±0.05, ±0.1, ±0.2, ±0.4 rad/s
  2. Pitch 低速匀速扫角: 同上
  3. 每个速度保持 2-3 秒
  4. 采集:
     python serial_collect.py friction --port COM7

  分析:
     python identify_gimbal.py friction friction_sweep.csv

  验证:
  - Yaw/Pitch 的 R² 应 > 0.90
  - 库仑摩擦 (theta6, theta8) 应为正值

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Step 3: Pitch 惯量辨识 (theta2)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  目标: 辨识 Pitch 等效惯量

  操作:
  1. Yaw 锁定在 q1=0
  2. Pitch 做低频平滑加减速 (0.1-0.3 Hz 正弦)
  3. 幅值: 0.2-0.4 rad
  4. 采集:
     python serial_collect.py dynamic --port COM7 --output dynamic_pitch.csv

  分析:
     python identify_gimbal.py pitch dynamic_pitch.csv

  验证:
  - R² 应 > 0.85
  - theta2 应为正值

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Step 4: 耦合惯量辨识 (theta0, theta1)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  目标: 辨识 Yaw-Pitch 耦合惯量

  操作:
  1. 固定 Pitch 到多个角度: -25°, -10°, 0°, 10°, 25°
  2. 每个角度下，Yaw 做低频平滑加减速
  3. 每个姿态采集一组数据
  4. 保存为: dynamic_yaw_q2_m25.csv, dynamic_yaw_q2_m10.csv, ...

  分析:
     python identify_gimbal.py coupling dynamic_yaw_q2_*.csv

  验证:
  - 必须覆盖足够大的 Pitch 角度范围，否则 theta0/theta1 无法分离
  - R² 应 > 0.80

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Step 5: 五次谐波综合验证
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  目标: 验证全部参数的综合效果

  操作:
  1. 将辨识参数写入 params.hpp 的 kIdentTheta[9]
  2. 重新编译烧录
  3. 遥控器切换到辨识模式 (左 DOWN + 右 UP)
  4. 采集双轴五次谐波轨迹数据

  分析:
     python identify_gimbal.py verify dynamic_harmonics.csv

  验证:
  - Yaw RMSE < 0.5 Nm
  - Pitch RMSE < 0.5 Nm
  - 比较前馈开/关的跟踪误差

【常见问题】
  Q: 重力补偿方向反了?
  A: 检查 q2 正方向、tau2 正方向、theta3/theta4 符号

  Q: 摩擦拟合很乱?
  A: 检查速度稳定性，剔除零速附近数据，确保 Pitch 已扣重力

  Q: 惯量为负?
  A: 检查 ddq 是否由噪声差分得到，轨迹是否跟丢，先置零 theta2

  Q: 五次谐波 R² 高但实机效果差?
  A: 回到分步辨识，先验证重力，再验证摩擦，最后验证动态

【参数部署顺序】
  1. 只打开 theta3/theta4 (重力)，验证静态悬停
  2. 加入 theta5-theta8 (摩擦)，验证低速扫角
  3. 加入 theta2 (Pitch 惯量)，验证动态跟踪
  4. 最后加入 theta0/theta1 (耦合)，验证双轴动态
"""
    print(guide)


# ─────────────────────────── CLI ───────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Hero 云台动力学参数辨识工具",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  %(prog)s guide                          显示操作指导
  %(prog)s gravity  gravity_static.csv    重力项辨识
  %(prog)s friction friction_sweep.csv    摩擦项辨识
  %(prog)s pitch    dynamic_pitch.csv     Pitch 惯量辨识
  %(prog)s coupling yaw_q2_*.csv          耦合惯量辨识
  %(prog)s verify   harmonics.csv         五次谐波验证
""",
    )
    parser.add_argument("mode", choices=["guide", "gravity", "friction", "pitch", "coupling", "verify"],
                        help="辨识阶段")
    parser.add_argument("files", nargs="*", help="输入 CSV 文件")
    parser.add_argument("--output", "-o", help="输出 theta 文件")
    parser.add_argument("--gravity", nargs=2, type=float, metavar=("THETA3", "THETA4"),
                        help="已知重力参数 (用于摩擦/惯量/耦合辨识)")
    parser.add_argument("--friction", nargs=4, type=float, metavar=("T5", "T6", "T7", "T8"),
                        help="已知摩擦参数 (用于惯量/耦合辨识)")

    args = parser.parse_args()

    if args.mode == "guide":
        print_guide()
        return

    if not args.files:
        print("[ERROR] 需要提供 CSV 文件")
        parser.print_help()
        sys.exit(1)

    if args.mode == "gravity":
        df = load_csv(args.files[0])
        theta = identify_gravity(df)
        if args.output:
            save_theta(theta, args.output)

    elif args.mode == "friction":
        df = load_csv(args.files[0])
        if args.gravity:
            theta3, theta4 = args.gravity
        else:
            print("[INFO] 未提供重力参数，使用 theta3=0, theta4=0")
            theta3, theta4 = 0.0, 0.0
        theta = identify_friction(df, theta3, theta4)
        if args.output:
            save_theta(theta, args.output)

    elif args.mode == "pitch":
        df = load_csv(args.files[0])
        if args.gravity:
            theta3, theta4 = args.gravity
        else:
            theta3, theta4 = 0.0, 0.0
        if args.friction:
            theta7, theta8 = args.friction[2], args.friction[3]
        else:
            theta7, theta8 = 0.0, 0.0
        theta = identify_pitch_inertia(df, theta3, theta4, theta7, theta8)
        if args.output:
            save_theta(theta, args.output)

    elif args.mode == "coupling":
        if args.friction:
            theta5, theta6 = args.friction[0], args.friction[1]
        else:
            theta5, theta6 = 0.0, 0.0
        theta = identify_coupling(args.files, theta5, theta6)
        if args.output:
            save_theta(theta, args.output)

    elif args.mode == "verify":
        df = load_csv(args.files[0])
        if args.gravity and args.friction:
            theta = np.zeros(9)
            theta[3], theta[4] = args.gravity
            theta[5], theta[6], theta[7], theta[8] = args.friction
        else:
            print("[INFO] 未提供完整参数，使用全零 theta")
            theta = np.zeros(9)
        verify_harmonics(df, theta)


if __name__ == "__main__":
    main()
