#pragma once

#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>

#include <librm.hpp>

#include "lqr.hpp"
#include "../../tools/leso/generated/leso_model_generated.hpp"

namespace chassis::wbr {

struct LesoModelMatrices {
  std::array<rm::f32, 25> mass{};
  std::array<rm::f32, 25> gravity{};
  std::array<rm::f32, 20> input_map{};
  std::array<rm::f32, 20> disturbance_map{};
};

/**
 * @brief Evaluate the scheduled five-DOF model generated by the offline LESO tool.
 *
 * All matrices are row-major. The fitted fields use four leg-length regions and
 * the basis [1, l_l, l_r, l_l^2, l_l*l_r, l_r^2].
 */
class ScheduledLesoModel {
 public:
  [[nodiscard]] static LesoModelMatrices Evaluate(const rm::f32 left_leg_length_m, const rm::f32 right_leg_length_m) {
    namespace generated = wheel_legged::params::generated;

    const rm::f32 l_l = std::clamp(left_leg_length_m, generated::kLesoModelLegMinM, generated::kLesoModelLegMaxM);
    const rm::f32 l_r = std::clamp(right_leg_length_m, generated::kLesoModelLegMinM, generated::kLesoModelLegMaxM);
    const std::array<rm::f32, 6> basis{1.0f, l_l, l_r, l_l * l_l, l_l * l_r, l_r * l_r};

    int region = 0;
    if (l_l > generated::kLesoModelRegionSplitM) region += 1;
    if (l_r > generated::kLesoModelRegionSplitM) region += 2;

    LesoModelMatrices result{};
    EvaluateField(generated::kLesoM, region, basis, result.mass);
    EvaluateField(generated::kLesoG, region, basis, result.gravity);
    EvaluateField(generated::kLesoBTau, region, basis, result.input_map);
    EvaluateField(generated::kLesoDisturbanceMap, region, basis, result.disturbance_map);
    return result;
  }

 private:
  template <std::size_t CoefficientCount, std::size_t ElementCount>
  static void EvaluateField(const std::array<float, CoefficientCount> &coefficients, const int region,
                            const std::array<rm::f32, 6> &basis, std::array<rm::f32, ElementCount> &output) {
    constexpr std::size_t kBasisSize = 6;
    static_assert(CoefficientCount == 4 * ElementCount * kBasisSize);
    const std::size_t region_offset = static_cast<std::size_t>(region) * ElementCount * kBasisSize;
    for (std::size_t element = 0; element < ElementCount; ++element) {
      rm::f32 value = 0.0f;
      const std::size_t coefficient_offset = region_offset + element * kBasisSize;
      for (std::size_t coefficient = 0; coefficient < kBasisSize; ++coefficient) {
        value += coefficients[coefficient_offset + coefficient] * basis[coefficient];
      }
      output[element] = value;
    }
  }
};

struct MomentumLesoInput {
  CurrentState state{};
  rm::f32 left_leg_rate_mps{0.0f};
  rm::f32 right_leg_rate_mps{0.0f};
  rm::f32 wheel_radius_m{0.0575f};
  rm::f32 half_track_m{0.2025f};
  rm::f32 dt_s{0.002f};
  std::array<rm::f32, 4> previous_final_virtual_command{};
};

struct MomentumLesoOutput {
  std::array<rm::f32, 5> generalized_position{};
  std::array<rm::f32, 5> generalized_velocity{};
  std::array<rm::f32, 5> measured_momentum{};
  std::array<rm::f32, 5> estimated_momentum{};
  std::array<rm::f32, 5> generalized_disturbance{};
  std::array<rm::f32, 4> virtual_disturbance{};
  bool initialized{false};
};

/**
 * @brief Second-order linear extended-state observer in generalized momentum coordinates.
 */
class MomentumLeso {
 public:
  void Reset() { output_ = {}; }

  [[nodiscard]] const MomentumLesoOutput &Update(const MomentumLesoInput &input) {
    if (!InputIsValid(input)) {
      Reset();
      return output_;
    }

    const LesoModelMatrices model = ScheduledLesoModel::Evaluate(input.state.l_l, input.state.l_r);
    BuildGeneralizedState(input, output_.generalized_position, output_.generalized_velocity);
    Multiply<5, 5>(model.mass, output_.generalized_velocity, output_.measured_momentum);

    if (!output_.initialized) {
      output_.estimated_momentum = output_.measured_momentum;
      output_.generalized_disturbance.fill(0.0f);
      output_.virtual_disturbance.fill(0.0f);
      output_.initialized = true;
      return output_;
    }

    std::array<rm::f32, 5> nominal_momentum_rate{};
    std::array<rm::f32, 5> input_term{};
    std::array<rm::f32, 5> gravity_term{};
    Multiply<5, 4>(model.input_map, input.previous_final_virtual_command, input_term);
    Multiply<5, 5>(model.gravity, output_.generalized_position, gravity_term);

    for (std::size_t i = 0; i < 5; ++i) {
      nominal_momentum_rate[i] = input_term[i] - gravity_term[i];
      const rm::f32 error = output_.measured_momentum[i] - output_.estimated_momentum[i];
      const rm::f32 omega = wheel_legged::params::leso::kBandwidthRadS[i];
      const rm::f32 beta1 = 2.0f * omega;
      const rm::f32 beta2 = omega * omega;

      output_.generalized_disturbance[i] = std::clamp(output_.generalized_disturbance[i] + beta2 * error * input.dt_s,
                                                      -wheel_legged::params::leso::kGeneralizedDisturbanceLimit,
                                                      wheel_legged::params::leso::kGeneralizedDisturbanceLimit);
      output_.estimated_momentum[i] +=
          (nominal_momentum_rate[i] + output_.generalized_disturbance[i] + beta1 * error) * input.dt_s;
    }

    if (!OutputIsFinite()) {
      Reset();
      return output_;
    }

    Multiply<4, 5>(model.disturbance_map, output_.generalized_disturbance, output_.virtual_disturbance);
    for (rm::f32 &disturbance : output_.virtual_disturbance) {
      disturbance = std::clamp(disturbance, -wheel_legged::params::leso::kVirtualDisturbanceLimit,
                               wheel_legged::params::leso::kVirtualDisturbanceLimit);
    }
    return output_;
  }

  [[nodiscard]] const MomentumLesoOutput &output() const { return output_; }

 private:
  template <std::size_t Rows, std::size_t Columns>
  static void Multiply(const std::array<rm::f32, Rows * Columns> &matrix, const std::array<rm::f32, Columns> &vector,
                       std::array<rm::f32, Rows> &result) {
    result.fill(0.0f);
    for (std::size_t row = 0; row < Rows; ++row) {
      for (std::size_t column = 0; column < Columns; ++column) {
        result[row] += matrix[row * Columns + column] * vector[column];
      }
    }
  }

  static void BuildGeneralizedState(const MomentumLesoInput &input, std::array<rm::f32, 5> &q,
                                    std::array<rm::f32, 5> &dq) {
    const CurrentState &x = input.state;
    const rm::f32 left_coupling = 0.5f * x.l_l * x.theta_ll;
    const rm::f32 right_coupling = 0.5f * x.l_r * x.theta_lr;
    const rm::f32 left_coupling_rate = 0.5f * (input.left_leg_rate_mps * x.theta_ll + x.l_l * x.theta_ll_dot);
    const rm::f32 right_coupling_rate = 0.5f * (input.right_leg_rate_mps * x.theta_lr + x.l_r * x.theta_lr_dot);

    q[0] = (x.s - input.half_track_m * x.phi - left_coupling + right_coupling) / input.wheel_radius_m;
    q[1] = (x.s + input.half_track_m * x.phi + left_coupling - right_coupling) / input.wheel_radius_m;
    q[2] = x.theta_ll;
    q[3] = x.theta_lr;
    q[4] = x.theta_b;

    dq[0] =
        (x.s_dot - input.half_track_m * x.phi_dot - left_coupling_rate + right_coupling_rate) / input.wheel_radius_m;
    dq[1] =
        (x.s_dot + input.half_track_m * x.phi_dot + left_coupling_rate - right_coupling_rate) / input.wheel_radius_m;
    dq[2] = x.theta_ll_dot;
    dq[3] = x.theta_lr_dot;
    dq[4] = x.theta_b_dot;
  }

  [[nodiscard]] static bool InputIsValid(const MomentumLesoInput &input) {
    if (!(input.dt_s > 0.0f) || !(input.wheel_radius_m > 1.0e-5f) || !(input.half_track_m > 1.0e-5f)) {
      return false;
    }
    const std::array<rm::f32, 16> values{
        input.state.s,           input.state.s_dot,        input.state.phi,      input.state.phi_dot,
        input.state.theta_ll,    input.state.theta_ll_dot, input.state.theta_lr, input.state.theta_lr_dot,
        input.state.theta_b,     input.state.theta_b_dot,  input.state.l_l,      input.state.l_r,
        input.left_leg_rate_mps, input.right_leg_rate_mps, input.wheel_radius_m, input.half_track_m,
    };
    return std::all_of(values.begin(), values.end(), [](const rm::f32 value) { return std::isfinite(value); }) &&
           std::all_of(input.previous_final_virtual_command.begin(), input.previous_final_virtual_command.end(),
                       [](const rm::f32 value) { return std::isfinite(value); });
  }

  [[nodiscard]] bool OutputIsFinite() const {
    return std::all_of(output_.estimated_momentum.begin(), output_.estimated_momentum.end(),
                       [](const rm::f32 value) { return std::isfinite(value); }) &&
           std::all_of(output_.generalized_disturbance.begin(), output_.generalized_disturbance.end(),
                       [](const rm::f32 value) { return std::isfinite(value); });
  }

  MomentumLesoOutput output_{};
};

}  // namespace chassis::wbr
