name: build-dart_rack

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          ref: ${{ github.sha }}
      - uses: ./.github/actions/build-target
        with:
          target: test_target
          build_type: ${{ env.BUILD_TYPE }}